fragment AccountItem on Account {
	id
	name
	type
	portfolioId
	provider
	externalId
	key
	description
	institution
	mode
	status
	optionLevel
	cashForOpenOrders
	balanceMoneyMarket
	cashAvailableForInvestment
	current
	accountValueTotal
	marketValueTotal
	cashNet
	cashBalance
	balanceAccount
	createdAt
	updatedAt
	authConnection {
		id
		source
		plaidInstitutionId
	}
	createdBy {
		id
		...UserItem
	}
	_realizedProfitAndLoss {
		id
		shortTermCapitalGain
		longTermCapitalGain
		dividend
		qualifiedDividend
		nonQualifiedDividend
		dividendReinvestment
		interest
		interestReinvestment
		distribution
		accountFee
		managementFee
		fundFee
		taxWithheld
		nonResidentTax
		deposit
		withdrawal
		contribution
		returnOfPrincipal
		loanPayment
		marginExpense
		stockDistribution
		unqualifiedGain
		unrealizedLoss
		unrealizedProfit
	}
}

query Account($id: String!) {
	account(id: $id) {
		id
		...AccountItem
	}
}

mutation UpdateAccount(
	$accountUpdateInput: AccountUpdateInput!
	$accountWhereUniqueInput: AccountWhereUniqueInput!
) {
	updateAccount(
		accountUpdateInput: $accountUpdateInput
		accountWhereUniqueInput: $accountWhereUniqueInput
	) {
		id
		name
		portfolioId
		description
	}
}

mutation InsertAccountRealizedPAndL($input: RealizedPAndLCreateInput!) {
	insertRealizedPAndL(input: $input) {
		id
		shortTermCapitalGain
		longTermCapitalGain
		dividend
		qualifiedDividend
		nonQualifiedDividend
		dividendReinvestment
		interest
		interestReinvestment
		distribution
		accountFee
		managementFee
		fundFee
		taxWithheld
		nonResidentTax
		deposit
		withdrawal
		contribution
		returnOfPrincipal
		loanPayment
		marginExpense
		stockDistribution
		unqualifiedGain
		unrealizedLoss
		unrealizedProfit
	}
}

fragment LotItem on Lot {
	id
	acquiredDate
	costTotal
	price
	remainingQty
	assetSymbol
	totalCostForGainPct
	asset {
		symbol
		lastPrice
	}
	account {
		id
		externalId
		name
		type
	}
}

query AccountLots($accountId: String!) {
	lots(where: { accountId: { equals: $accountId } }) {
		id
		...LotItem
	}
}

mutation DeleteAccount($accountWhereUniqueInput: AccountWhereUniqueInput!) {
	deleteAccount(accountWhereUniqueInput: $accountWhereUniqueInput) {
		id
		name
	}
}

query AccountFiles($accountId: String!) {
	files(where: { accountId: { equals: $accountId } }) {
		id
		...AccountFileItem
	}
}

fragment AccountFileItem on File {
	id
	accountId
	displayName
	gcpFilename
	type
	createdAt
	updatedAt
}
