fragment LotUploadItem on LotUpload {
	id
	createdAt
	updatedAt
	portfolioId
	accountId
	applied
	supportedAccountLotProvider
	usePositionsAsLots
	LotUploadFile {
		id
		type
		fileId
		assetSymbol
		file {
			id
			displayName
		}
	}
}

query LotUploads($where: LotUploadWhereInput!) {
	lotUploads(where: $where) {
		...LotUploadItem
	}
}

mutation ApplyLotUploads($lotUploadIds: [String!]!) {
	applyLotUploads(lotUploadIds: $lotUploadIds)
}

mutation UploadLotFileSchwab($input: UploadLotFileInput!) {
	uploadLotFileSchwab(input: $input) {
		id
		type
		fileId
		assetSymbol
		file {
			id
			displayName
		}
	}
}

mutation UpdateLotUpload($lotUploadId: String!, $data: LotUploadUpdateInput!) {
	updateLotUpload(lotUploadId: $lotUploadId, data: $data) {
		...LotUploadItem
	}
}
