query LotUploads($where: LotUploadWhereInput!) {
  lotUploads(where: $where) {
    id
    createdAt
    applied
    supportedAccountLotProvider
    LotUploadFile {
      id
      type
      fileId
      file {
        id
        displayName
      }
    }
  }
}

mutation ApplyLotUpload($lotUploadId: String!) {
  applyLotUpload(lotUploadId: $lotUploadId)
}

mutation UploadLotFileSchwab($input: UploadLotFileInput!) {
  uploadLotFileSchwab(input: $input) {
    id
    type
    fileId
    file {
      id
      displayName
    }
  }
}