fragment MultiChangeSetTableItem on MergeError {
	id
	portfolioId
	accountId
	assetSymbol
	type
	targetValue
	targetQuantity
	resolved
	createdAt
	updatedAt
}

fragment MultiChangeSetDetail on MergeError {
	id
	portfolioId
	accountId
	assetSymbol
	type
	targetValue
	targetQuantity
	lotsData
	lotChangeSetAlgoParams
	logId
	resolved
	createdAt
	updatedAt
	AssetMerge {
		id
		targetValue
		targetQuantity
		targetPositionSnapshot
		lotData
		resolvedLotChange
		error
		createdAt
		updatedAt
		plaidMerge {
			id
			resolveLotsInput
			createdAt
			updatedAt
		}
		transactionOnAssetMerge {
			transaction {
				id
				externalId
				type
				subtype
				transactionDate
				description
				assetSymbol
				quantity
				price
				amount
			}
		}
		lotChangeList {
			id
			LotChange {
				id
				quantityFinal
				quantityChange
				assetSymbol
				upsert
				operationType
				lot {
					id
					remainingQty
					price
					acquiredDate
				}
			}
		}
	}
}

query MergeErrors {
	mergeErrors {
		...MultiChangeSetTableItem
	}
}

query AdminMergeErrors {
	adminMergeErrors {
		...MultiChangeSetTableItem
	}
}

query MergeError($id: String!) {
	mergeError(id: $id) {
		...MultiChangeSetDetail
	}
}

mutation UpdateMergeError($id: String!, $data: MergeErrorUpdateInput!) {
	updateMergeError(id: $id, data: $data) {
		...MultiChangeSetDetail
	}
}
