query SignedUrlsForUpload($files: [GCPUploadFile!]!) {
  generateSignedUrlsForUpload(files: $files) {
    uploadUrls
  }
}

query SignedUrlsForDownload($gcpFileNames: [String!]!) {
  genrerateSignedUrlsForDownload(gcpFileNames: $gcpFileNames) {
    downloadUrls
  }
}

fragment FileItem on File {
  id
  accountId
  displayName
  gcpFilename
  type
}

mutation CreateFiles($data: [FileCreateManyInput!]!) {
  createFiles(data: $data) {
    id
    ...FileItem
  }
}

mutation InitAccountFileUpload($fileData: [InitFileUploadPayload!]!, $accountData: InitAccountFileUploadPayload!) {
  initAccountFileUpload(fileData: $fileData, accountData: $accountData) {
    id
    ...FileItem
  }
}
