fragment AccountSummary on Account {
	id
	uploadedPositions
	setRealizedValues
	name
	type
	subType
	accountValueTotal
	skipSetup
}

query PortfolioSummary {
	portfolioSummary {
		realized {
			dividend
			longTermCapitalGain
			shortTermCapitalGain
			gainTotal
			estimatedTaxBill {
				total
				shortTermCapitalGain {
					total
					rate
					result
				}
				longTermCapitalGain {
					total
					rate
					result
				}
				dividend {
					total
					rate
					result
				}
				qualifiedDividend {
					total
					rate
					result
				}
				nonQualifiedDividend {
					total
					rate
					result
				}
				dividendReinvestment {
					total
					rate
					result
				}
				interest {
					total
					rate
					result
				}
				interestReinvestment {
					total
					rate
					result
				}
				distribution {
					total
					rate
					result
				}
				accountFee {
					total
					rate
					result
				}
				managementFee {
					total
					rate
					result
				}
				fundFee {
					total
					rate
					result
				}
				taxWithheld {
					total
					rate
					result
				}
				nonResidentTax {
					total
					rate
					result
				}
				deposit {
					total
					rate
					result
				}
				withdrawal {
					total
					rate
					result
				}
				contribution {
					total
					rate
					result
				}
				returnOfPrincipal {
					total
					rate
					result
				}
				loanPayment {
					total
					rate
					result
				}
				marginExpense {
					total
					rate
					result
				}
				stockDistribution {
					total
					rate
					result
				}
				unqualifiedGain {
					total
					rate
					result
				}
			}
		}
		unrealized {
			gainTotal
			lossTotal
			accountCount
			positionCount
		}
		harvest {
			realized
			unrealized
			total
		}
		setUpStatus
	}
}

query AccountSummaries {
	accounts {
		id
		...AccountSummary
	}
}

query AccountRealizedPL {
	accounts {
		id
		name
		realizedPAndL {
			id
			shortTermCapitalGain
			longTermCapitalGain
			dividend
			createdAt
		}
	}
}

query PortfolioPerformanceByAccount($timeSpan: PerformanceTimeSpan!) {
	portfolioPerformanceByAccount(input: { timeSpan: $timeSpan }) {
		date
		portfolioTotal
		accounts {
			accountId
			accountName
			valueTotal
			valueCash
			valueAssets
			realizedPAndLShortTerm
			realizedPAndLLongTerm
			unrealizedProfit
			unrealizedLoss
		}
	}
}

query PortfolioPerformanceByPosition(
	$timeSpan: PerformanceTimeSpan!
	$symbols: [String!]
) {
	portfolioPerformanceByPosition(
		input: { timeSpan: $timeSpan, symbols: $symbols }
	) {
		date
		portfolioTotal
		positions {
			symbol
			value
			shares
		}
	}
}
