fragment AccountSummary on Account {
	id
	uploadedPositions
	setRealizedValues
	name
	type
	subType
	accountValueTotal
	skipSetup
}

query PortfolioSummary {
	portfolioSummary {
		realized {
			dividend
			longTermCapitalGain
			shortTermCapitalGain
			gainTotal
		}
		unrealized {
			gainTotal
			lossTotal
			accountCount
			positionCount
		}
		harvest {
			realized
			unrealized
			total
		}
		setUpStatus
	}
}

query AccountSummaries {
	accounts {
		id
		...AccountSummary
	}
}

query AccountRealizedPL {
	accounts {
		id
		name
		realizedPAndL {
			id
			shortTermCapitalGain
			longTermCapitalGain
			dividend
			createdAt
		}
	}
}

query PortfolioPerformanceByAccount($timeSpan: PerformanceTimeSpan!) {
	portfolioPerformanceByAccount(input: { timeSpan: $timeSpan }) {
		date
		portfolioTotal
		accounts {
			accountId
			accountName
			valueTotal
			valueCash
			valueAssets
			realizedPAndLShortTerm
			realizedPAndLLongTerm
			unrealizedProfit
			unrealizedLoss
		}
	}
}

query PortfolioPerformanceByPosition(
	$timeSpan: PerformanceTimeSpan!
	$symbols: [String!]
) {
	portfolioPerformanceByPosition(
		input: { timeSpan: $timeSpan, symbols: $symbols }
	) {
		date
		portfolioTotal
		positions {
			symbol
			value
			shares
		}
	}
}
