kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-weight: '-150'
spec:
  provider:
    gcpsm:
      projectID: harvester-ai-428202
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: google-secret-service-account
            namespace: harvester-dev
          clusterLocation: us-central1-b
          clusterName: harvester-dev
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
--
    kind: ClusterSecretStore
  target:
    name: database
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: DATABASE_NAME
      remoteRef:
        key: DATABASE_NAME
    - secretKey: DATABASE_HOST
      remoteRef:
        key: DATABASE_HOST
    - secretKey: DATABASE_PORT
      remoteRef:
        key: DATABASE_PORT
    - secretKey: DATABASE_USER
      remoteRef:
        key: DATABASE_USER
    - secretKey: DATABASE_PASSWORD
--
    kind: ClusterSecretStore
  target:
    name: clerk
    creationPolicy: Owner
  data:
    - secretKey: CLERK_SECRET_KEY
      remoteRef:
        key: CLERK_SECRET_KEY
    - secretKey: CLERK_USER_UPDATE_CREATE_WEBHOOK_SIGN_SECRET
      remoteRef:
        key: CLERK_USER_UPDATE_CREATE_WEBHOOK_SIGN_SECRET
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stripe-external-secret
  namespace: harvester-dev
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-weight: '-90'
--
    kind: ClusterSecretStore
  target:
    name: stripe
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: STRIPE_SECRET_KEY
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: etrade-external-secret
  namespace: harvester-dev
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-weight: '-90'
spec:
  refreshInterval: "1h"
  secretStoreRef:
--
    kind: ClusterSecretStore
  target:
    name: etrade
    creationPolicy: Owner
  data:
    - secretKey: ETRADE_API_KEY
      remoteRef:
        key: ETRADE_API_KEY
    - secretKey: ETRADE_API_SECRET
      remoteRef:
        key: ETRADE_API_SECRET
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: polygon-external-secret
  namespace: harvester-dev
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-weight: '-90'
--
    kind: ClusterSecretStore
  target:
    name: polygon
    creationPolicy: Owner
  data:
    - secretKey: POLYGON_API_KEY
      remoteRef:
        key: POLYGON_API_KEY
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plaid-external-secret
  namespace: harvester-dev
  annotations:
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-weight: '-90'
spec:
  refreshInterval: "1h"
  secretStoreRef:
--
    kind: ClusterSecretStore
  target:
    name: plaid
    creationPolicy: Owner
  data:
    - secretKey: PLAID_SECRET_KEY
      remoteRef:
        key: PLAID_SECRET_KEY
    - secretKey: PLAID_CLIENT_ID
      remoteRef:
        key: PLAID_CLIENT_ID
