fragment LotTransactionBatch on LotTransactionBatch {
  id
  createdAt
  updatedAt
}

query LotTransactionBatches {
  lotTransactionBatches {
    id
    ...LotTransactionBatch
  }
}

fragment LotTransactionBatchDetails on LotTransactionBatch {
  id
  createdAt
  updatedAt
  positionsBefore
  positionsAfter
  holdingsPayload
  lotTupleMap
  initialLots
  newTransactions
  newBuys
  newSells
  lotChangeLog {
    id
    createdAt
    lotId
    accountId
    portfolioId
    lotBefore
    lotAfter
    operationType
    source
    processed
    quantityChange
    lotTransactionBatchId
    lot {
      id
      remainingQty
      price
      acquiredDate
      assetSymbol
      account {
        id
        name
      }
    }
  }
}

query LotTransactionBatch($lotTransactionBatchId: String!) {
  lotTransactionBatch(lotTransactionBatchId: $lotTransactionBatchId) {
    id
    ...LotTransactionBatchDetails
  }
}
