query PlaidMerges {
	plaidMerges {
		id
		createdAt
		updatedAt
		accountId
		account {
			id
			name
		}
		portfolioId
		assetMerge {
			id
			mergeError {
				id
				type
				resolved
			}
		}
	}
}

query PlaidMerge($plaidMergeId: String!) {
	plaidMerge(plaidMergeId: $plaidMergeId) {
		id
		createdAt
		updatedAt
		accountId
		portfolioId
		resolveLotsInput
		account {
			id
			name
			type
		}
		portfolio {
			id
			name
		}
		AccountRealizedPAndLHistory {
			id
			uuid
			createdAt
			value
			profitAndLossType
			transaction {
				id
				externalId
				transactionDate
				type
				subtype
				assetSymbol
				quantity
				price
				amount
			}
			lotChangeList {
				id
				appliedToAccount
				LotChange {
					id
					lotId
					aquiredDate
					quantityFinal
					quantityChange
					price
					assetSymbol
					operationType
					realizedProfitAndLossShortTerm
					realizedProfitAndLossLongTerm
					lot {
						id
						acquiredDate
						price
						remainingQty
						assetSymbol
					}
				}
			}
		}
		assetMerge {
			id
			createdAt
			assetSymbol
			targetValue
			targetQuantity
			positionSnapshot {
				id
			}
			lotData
			resolvedLotChange
			error
			asset {
				symbol
				name
				lastPrice
			}
			mergeError {
				id
				type
				resolved
			}
			lotChangeList {
				id
				appliedToAccount
				LotChange {
					id
					lotId
					aquiredDate
					quantityFinal
					quantityChange
					price
					assetSymbol
					operationType
					realizedProfitAndLossShortTerm
					realizedProfitAndLossLongTerm
					lot {
						id
						acquiredDate
						price
						remainingQty
					}
				}
			}
			transactionOnAssetMerge {
				transaction {
					id
					externalId
					transactionDate
					type
					subtype
					assetSymbol
					quantity
					price
					amount
				}
			}
		}
	}
}
