apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harvester-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.namespace }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    {{- range .Values.global.ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ if eq .service "argocd-server" }}{{ .service }}{{ else }}{{ $.Release.Name }}-{{ .service }}{{ end }}
                port:
                  {{- if .port }}
                  name: {{ .port }}
                  {{- else }}
                  number: 80
                  {{- end }}
          {{- end }}
    {{- end }} 