{{- if .Values.global.ingress.enabled -}}
{{- range .Values.global.certificates }}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Values.global.namespace }}
  labels:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  domains:
    {{- range .domains }}
    - {{ . }}
    {{- end }}
{{- end }}
{{- end -}} 