{{- if and .Values.global.ingress.enabled .Values.global.ingress.useManagedCertificates -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: harvester-cert
  namespace: {{ .Values.global.namespace | default "harvester" }}
  labels:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  domains:
    - {{ .Values.global.domain }}
{{- end -}} 