{{- range .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .gcpServiceAccount }}@{{ $.Values.global.projectID }}.iam.gserviceaccount.com
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-200"
{{- end }} 