# mutation GenerateEmbeddings($startDate: DateTime!) {
#   generateEmbeddings(startDate: $startDate)
# }

# mutation UpdateHourlyAssetPrices($from: DateTime!, $to: DateTime!) {
#   updateHourlyAssetPrices(from: $from, to: $to)
# }

mutation UpdateAllAssetPrices {
  updateAllAssetPrices
}

mutation SendWashSaleNotificationsForDate($date: DateTime!) {
  sendWashSaleNotificationsForDate(date: $date)
}

mutation SendNotificationsByFrequency(
  $frequency: HarvestNotificationFrequency!
) {
  sendNotificationsByFrequency(frequency: $frequency)
}
