# mutation GenerateEmbeddings($startDate: DateTime!) {
#   generateEmbeddings(startDate: $startDate)
# }

# mutation UpdateHourlyAssetPrices($from: DateTime!, $to: DateTime!) {
#   updateHourlyAssetPrices(from: $from, to: $to)
# }

mutation UpdateAllAssetPrices {
	updateAllAssetPrices
}

mutation SendWashSaleNotificationsForDate($date: DateTime!) {
	sendWashSaleNotificationsForDate(date: $date)
}

mutation SendNotificationsByFrequency(
	$frequency: HarvestNotificationFrequency!
) {
	sendNotificationsByFrequency(frequency: $frequency)
}

query AdminPlaidAuthConnections {
	plaidAuthConnections {
		id
		plaidInstitutionId
		authedAt
		syncedAt
		portfolioId
		user {
			id
			email
			phoneNumber
		}
		accounts {
			id
			name
			plaidAccountMask
			type
			subType
			status
			balanceAccount
			accountValueTotal
		}
	}
}

mutation AdminSyncPlaidItem($authConnectionId: String!) {
	adminSyncPlaidItem(authConnectionId: $authConnectionId)
}
