{{- define "common.migrations" -}}
{{- if .Values.migrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" . }}-migrations
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: -50
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 30
  {{- if .Values.migrations.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.migrations.activeDeadlineSeconds }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
    spec:
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}
      shareProcessNamespace: true
      restartPolicy: Never
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.migrations.command | toJson }}
          args: {{ .Values.migrations.args | toJson }}
          env:
            # Add Cloud SQL instance connection name as an environment variable
            {{- if and (hasKey .Values.migrations "cloudsql") .Values.migrations.cloudsql.enabled }}
            - name: INSTANCE_CONNECTION_NAME
              value: {{ .Values.migrations.cloudsql.instanceConnectionName | quote }}
            {{- end }}
            {{- if .Values.env.extras }}
            {{- range $key, $value := .Values.env.extras }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.migrations.env }}
            {{- if .Values.migrations.env.extras }}
            {{- range $key, $value := .Values.migrations.env.extras }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.env.secretRefs }}
            {{- range .Values.env.secretRefs }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
            {{- end }}
            {{- if .Values.migrations.secretRefs }}
            {{- range .Values.migrations.secretRefs }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
            {{- end }}
          # {{- if hasKey .Values "cloudsql" }}
          # {{- if .Values.cloudsql.enabled }}
          # volumeMounts:
          #   - name: cloudsql
          #     mountPath: /cloudsql
          # {{- end }}
          # {{- end }}
        {{- if hasKey .Values "cloudsql" }}
        {{- if .Values.cloudsql.enabled }}
        # Cloud SQL Auth Proxy sidecar container
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--private-ip"
            # - "--unix-socket=/cloudsql"
            - "--port={{ .Values.cloudsql.port | default "5432" }}"
            # Enable the admin api server on port 9091
            - "--admin-port=9091"
            # Enable the /quitquitquit admin api endpoint
            - "--quitquitquit"
            # Tell the proxy to exit gracefully if it receives a SIGTERM
            - "--exit-zero-on-sigterm"
            - "{{ .Values.cloudsql.instanceConnectionName }}"
          # volumeMounts:
          #   - name: cloudsql
          #     mountPath: /cloudsql
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 1"]
          resources:
            {{- toYaml .Values.cloudsql.resources | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- if or (and (hasKey .Values "cloudsql") .Values.cloudsql.enabled) (and (hasKey .Values.migrations "cloudsql") .Values.migrations.cloudsql.enabled) }}
      volumes:
        - name: cloudsql
          emptyDir: {}
        {{- if and (hasKey .Values "cloudsql") .Values.cloudsql.enabled .Values.cloudsql.credentials }}
        - name: cloudsql-instance-credentials
          secret:
            secretName: {{ .Values.cloudsql.credentials.secretName }}
        {{- end }}
        {{- if and (hasKey .Values.migrations "cloudsql") .Values.migrations.cloudsql.enabled .Values.migrations.cloudsql.credentials }}
        - name: cloudsql-instance-credentials
          secret:
            secretName: {{ .Values.migrations.cloudsql.credentials.secretName }}
        {{- end }}
      {{- end }}
{{- end -}}
{{- end -}} 