{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: harvester-cert
  namespace: {{ .Values.global.namespace | default "harvester" }}
  annotations:
    # This ensures the certificate is created before ingress
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  domains:
    - {{ .Values.global.domain }}
{{- end -}} 