apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.global.projectID }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.serviceAccountName }}
            namespace: {{ .Values.global.namespace }}
          clusterLocation: {{ .Values.global.clusterLocation | default "us-central1-b" }}
          clusterName: {{ .Values.global.clusterName | default "harvester-dev" }}
