apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-studio
  namespace: harvester
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            path: /studio
            backend:
              service:
                name: harvester-studio
                port:
                  name: http
