{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: {{ .Values.namespace | default "argocd" }}
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
{{- end }} 