fragment HarvestLotOrderItem on HarvestLotOrder {
  accountId
  costBasis
  gainTotal
  id
  lotId
  pricePaid
  quantity
  taxGain
  assetSymbol
  dollarPerSharePnL
  valueTotal
  orderType
  acquiredDate
}

query HarvestEval {
  harvestEval {
    realizedOrders {
      ...HarvestLotOrderItem
    }
    unrealizedOrders {
      ...HarvestLotOrderItem
    }
    portfolioSummary {
      realized {
        accountCount
        dividend
        gainLongTerm
        gainShortTerm
        gainTotal
      }
      unrealized {
        gainTotal
        lossTotal
        accountCount
        positionCount
      }
      harvest {
        realized
        unrealized
        total
      }
    }
  }
}
