fragment AccountTableItem on Account {
	id
	name
	type
	portfolioId
	provider
	externalId
	key
	institution
	mode
	status
	optionLevel
	cashForOpenOrders
	balanceMoneyMarket
	current
	cashNet
	cashBalance
	balanceAccount
	createdAt
	updatedAt
	createdBy {
		id
		...UserItem
	}
	authConnectionId
	# authConnectionExt {
	#   ...AccountTableAuthConnection
	# }
}

query Accounts($where: AccountWhereInput) {
	accounts(where: $where) {
		id
		...AccountTableItem
		positions {
			id
			gainTotal
		}
	}
}

mutation CreateAccountForPortfolio($accountCreateInput: AccountCreateInput!) {
	createAccountForPortfolio(accountCreateInput: $accountCreateInput) {
		id
		...AccountTableItem
	}
}

mutation SyncAccount($authConnectionId: String!) {
	syncAuthConnection(id: $authConnectionId) {
		id
	}
}
