fragment AccountTableItem on Account {
	id
	name
	type
	portfolioId
	provider
	externalId
	key
	mode
	status
	optionLevel
	cashForOpenOrders
	balanceMoneyMarket
	current
	cashNet
	cashBalance
	balanceAccount
	createdAt
	updatedAt
	createdBy {
		id
		...UserItem
	}
	authConnectionId
	portfolioConnect {
		plaidInstitution {
			id
			name
			logo
			primaryColor
		}
	}
}

query Accounts($where: AccountWhereInput) {
	accounts(where: $where) {
		id
		...AccountTableItem
		positions {
			id
			gainTotal
		}
	}
}

mutation CreateAccountForPortfolio($accountCreateInput: AccountCreateInput!) {
	createAccountForPortfolio(accountCreateInput: $accountCreateInput) {
		id
		...AccountTableItem
	}
}
