fragment FiniteHarvestLotOrderItem on HarvestLotOrder {
  accountId
  costBasis
  gainTotal
  id
  lotId
  pricePaid
  quantity
  taxGain
  assetSymbol
  dollarPerSharePnL
  valueTotal
  orderType
  acquiredDate
}

query LotFilteredOpportunities {
  finiteHarvest {
    allOrders {
      id
      ...FiniteHarvestLotOrderItem
    }
    portfolioSummary {
    realized {
      accountCount
      dividend
      gainLongTerm
      gainShortTerm
      gainTotal
    }
    unrealized {
      gainTotal
      lossTotal
      accountCount
      positionCount
    }
    harvest {
      realized
      unrealized
      total
    }
    setUpStatus
    harvestRecommendations {
      harvestType
      amountRealized
          amountTotal
        amountUnrealized
        recommended
      }
    }
  }
}
