fragment FiniteHarvestLotItem on LotCurrent {
	id
	accountId
	remainingQty
	acquiredDate
	price
	symbol
	lastPrice
	costBasis
	value
	gainTotal
	gainTotalPct
	dollarPerSharePnL
	taxGain
	currentHarvestQty
	availableQty
}

fragment HarvestLotItem on HarvestLotCurrent {
	id
	accountId
	remainingQty
	acquiredDate
	price
	symbol
	lastPrice
	costBasis
	value
	gainTotal
	gainTotalPct
	dollarPerSharePnL
	taxGain
	currentHarvestQty
	harvestQuantity
	harvestPAndL
	availableQty
}

fragment MatchedLotOrderItem on HarvestLotOrder {
	accountId
	costBasis
	gainTotal
	id
	lotId
	pricePaid
	quantity
	taxGain
	assetSymbol
	dollarPerSharePnL
	valueTotal
	orderType
	acquiredDate
	lastPrice
}

mutation DeleteHarvests($ids: [String!]!) {
	deleteHarvests(ids: $ids)
}

fragment HarvestEvalResultFragment on HarvestEvalResult {
	harvestType
	neutralHarvestTarget
	remainingHarvestTarget
	summary {
		realized {
			gainTotal
		}
		unrealized {
			gainTotal
			lossTotal
			total
		}
		includingCurrentHarvest {
			realized {
				gainTotal
			}
			unrealized {
				gainTotal
				lossTotal
			}
		}
	}
	lotsCurrent {
		id
		...FiniteHarvestLotItem
	}
	matchedItems {
		id
		pairs {
			sourceHarvestPAndL
			matchedHarvestPAndL
			sourceLots {
				id
				...HarvestLotItem
			}
			matchedLots {
				id
				...HarvestLotItem
			}
		}
	}
	totalHarvestLots
	uniqueAssetSymbols
}

query HarvestEvalResult($filters: HarvestEvalFilters) {
	harvestEvalResult(filters: $filters) {
		...HarvestEvalResultFragment
	}
}
