fragment HarvestLotCurrentItem on LotCurrent {
  id
  accountId
  remainingQty
  acquiredDate
  price
  symbol
  lastPrice
  costBasis
  value
  gainTotal
  gainTotalPct
  dollarPerSharePnL
  taxGain
}
query LotsCurrentForHarvest($lotValueType: LotValueType!) {
  lotCurrent(lotValueType: $lotValueType) {
    id
    ...HarvestLotCurrentItem
  }
  portfolioSummary {
    realized {
      gainTotal
    }
    unrealized {
      gainTotal
      lossTotal
      gainTotal
    }
  }
}
