{{ if .Values.migrationsJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "app.fullname" . }}
  labels: {{- include "app.labels" . | nindent 4 }}
  annotations: 
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      annotations: 
        "linkerd.io/inject": disabled
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/sh', '-c']
          args:
            - |
              set -e
              echo "Starting migrations..."
              chmod +x ./scripts/migrate.sh 
              ./scripts/migrate.sh
              echo "Migration script completed with status $?"
              exit 0
          # command:
          #   {{  range .Values.migrationsJob.containerCommand }}
          #     - {{ . }}
          #   {{ end }}
          # args:
          #   {{  range .Values.migrationsJob.containerArgs }}
          #     - {{ . }}
          #   {{ end }}
          env:
            {{- range $ind, $map := .Values.extraEnvVars }}
            - name: {{ $map.name }}
              {{- if $map.valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ $map.valueFrom.secretKeyRef.name }}
                  key: {{ $map.valueFrom.secretKeyRef.key }}
              {{- end }}
              {{- if $map.value }}
              value: {{ quote $map.value }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: cloud-sql-proxy
          restartPolicy: Always
          # See: https://github.com/GoogleCloudPlatform/cloudsql-proxy 
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          args:
            # If connecting from a VPC-native GKE cluster, you can use the
            # following flag to have the proxy connect over private IP
            - "--private-ip"
            # - "--auto-iam-authn"
            - "--port={{ .Values.cloudSqlProxy.port | default 5432 }}"
            - "harvester-ai-428202:us-central1:harvester-dev"
          securityContext:
            # The default Cloud SQL proxy image runs as the
            # "nonroot" user and group (uid: 65532) by default.
            runAsNonRoot: true
          # resources:
          #   requests:
          #     # The proxy's memory use scales linearly with the number of active
          #     # connections. Fewer open connections will use less memory. Adjust
          #     # this value based on your application's requirements.
          #     memory: "2Gi"
          #     # The proxy's CPU use scales linearly with the amount of IO between
          #     # the database and the application. Adjust this value based on your
          #     # application's requirements.
          #     cpu:    "1"
      restartPolicy: Never
{{ end }}