export const exampleLots = [
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 25,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 19.386,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2014-09-03 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 24.4994,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 40.001,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2014-09-04 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 50.8811,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.227,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2019-08-15 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 66.2286,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.175,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2019-11-14 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 81.3287,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.143,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-02-13 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 75.6707,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.164,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-05-14 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 114.2202,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.109,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-08-13 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 132.088,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-09-01 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 119.375,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.112,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-11-12 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 118.33,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 1,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-11-19 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 130.59,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-01-06 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 135.3704,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.108,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-02-11 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 124.6825,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.126,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-05-13 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 147.1028,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.107,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-08-12 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 148.6792,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.106,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-11-11 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 173.5165,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.091,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-02-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 142.5,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.116,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-05-12 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 170.6186,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.097,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-08-11 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 145.308,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-10-20 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 142.9839,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.124,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-11-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 154.3478,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.115,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-02-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 173.3645,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.107,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-05-18 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 175.283,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.106,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-08-17 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 174.538,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-08-21 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 188.5714,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.105,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-11-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 182.545,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 4,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-02-02 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 182.3684,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.114,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-02-15 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 188.5217,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.115,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-05-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 221.5306,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.098,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-08-15 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AAPL",
    externalId: null,
    excludeFromHarvest: 0,
    price: 224.1237,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.097,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-11-14 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "ABNB",
    externalId: null,
    excludeFromHarvest: 0,
    price: 115.95,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 9,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-09-03 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "ADBE",
    externalId: null,
    excludeFromHarvest: 0,
    price: 322.15,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 1,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-09-15 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "ADBE",
    externalId: null,
    excludeFromHarvest: 0,
    price: 322.19,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 14,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-09-15 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "ADBE",
    externalId: null,
    excludeFromHarvest: 0,
    price: 321.2225,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 4,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-09-15 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "ADBE",
    externalId: null,
    excludeFromHarvest: 0,
    price: 319.685,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-10-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "ADBE",
    externalId: null,
    excludeFromHarvest: 0,
    price: 295,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 8,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-11-03 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "ADBE",
    externalId: null,
    excludeFromHarvest: 0,
    price: 307.56,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-11-08 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "ADBE",
    externalId: null,
    excludeFromHarvest: 0,
    price: 481.9,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-12-12 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 154.55,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-11-23 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 157.57,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 20,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-14 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 145.38,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 145.46,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 8,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 176.699,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.103,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-02-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 151.5108,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.139,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-05-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 166.4567,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.127,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-08-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 149.48,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 10,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-11-02 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 152.6619,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.139,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-11-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 210,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.13,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-02-09 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 236.6667,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.135,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-05-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 232.1739,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.138,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-08-09 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "AXP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 286.9643,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.112,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-11-08 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CAVA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 86.47,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 27,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-06-06 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CAVA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 86.29,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 9,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-07-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CAVA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 79.248,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 15,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-07-18 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "COIN",
    externalId: null,
    excludeFromHarvest: 0,
    price: 246.66,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 4,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-10-13 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "COIN",
    externalId: null,
    excludeFromHarvest: 0,
    price: 333.22,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-11-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "COIN",
    externalId: null,
    excludeFromHarvest: 0,
    price: 333.285,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-11-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "COIN",
    externalId: null,
    excludeFromHarvest: 0,
    price: 72.0893,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 15,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-10-28 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "COIN",
    externalId: null,
    excludeFromHarvest: 0,
    price: 181.975,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 12,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-09-30 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CRWD",
    externalId: null,
    excludeFromHarvest: 0,
    price: 112.15,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 10,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-07 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CRWD",
    externalId: null,
    excludeFromHarvest: 0,
    price: 111.05,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 10,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CRWD",
    externalId: null,
    excludeFromHarvest: 0,
    price: 106.69,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-20 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CRWD",
    externalId: null,
    excludeFromHarvest: 0,
    price: 107.99,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-21 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CRWD",
    externalId: null,
    excludeFromHarvest: 0,
    price: 312.745,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-07-19 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "CRWD",
    externalId: null,
    excludeFromHarvest: 0,
    price: 230.96,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-08-06 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "IVW",
    externalId: null,
    excludeFromHarvest: 0,
    price: 95.1567,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-09-23 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "IVW",
    externalId: null,
    excludeFromHarvest: 0,
    price: 88,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.005,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-09-30 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "IVW",
    externalId: null,
    excludeFromHarvest: 0,
    price: 95.44,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-09-30 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "IVW",
    externalId: null,
    excludeFromHarvest: 0,
    price: 95.776,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-10-08 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "IVW",
    externalId: null,
    excludeFromHarvest: 0,
    price: 95.76,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-10-08 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "IVW",
    externalId: null,
    excludeFromHarvest: 0,
    price: 104.5899,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-12-12 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "KVYO",
    externalId: null,
    excludeFromHarvest: 0,
    price: 34.971,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 50,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-11-07 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "MSTR",
    externalId: null,
    excludeFromHarvest: 0,
    price: 427.854,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-11-22 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 15.8986,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 90,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-07 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 16.537,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 50,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 15.899,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 50,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-20 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 25.3333,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.03,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-03-29 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 38,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.02,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-06-30 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 38,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.02,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-09-28 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 38,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.02,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-12-28 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 76,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.01,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-03-27 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 118.75,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.016,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-06-28 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVDA",
    externalId: null,
    excludeFromHarvest: 0,
    price: 118.75,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.016,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-10-03 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVO",
    externalId: null,
    excludeFromHarvest: 0,
    price: 125.48,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 11,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-04-15 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVO",
    externalId: null,
    excludeFromHarvest: 0,
    price: 129,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-07-18 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "NVO",
    externalId: null,
    excludeFromHarvest: 0,
    price: 135.3846,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.039,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-08-26 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "QQQ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 444.4533,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-08-06 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "QQQ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 507.5,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.004,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-10-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 30.5415,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 60,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2019-09-26 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 46,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 100,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-03-06 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 107.36,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 20,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-09-02 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 101.596,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 20,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2020-09-03 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 147.625,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 10,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2021-08-23 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 27.3583,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 6,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-09-30 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 69.55,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-04-15 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 74.99,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 1,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-05-06 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 61.7991,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 23,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-05-08 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 57.4463,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 30,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-05-14 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SHOP",
    externalId: null,
    excludeFromHarvest: 0,
    price: 60.628,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 10,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-06-05 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 362.0695,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 23.001,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-09-30 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 387.47,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 4,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-10-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 404.3267,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-14 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 382.6167,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 378.21,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 20,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-20 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 401.8045,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.133,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-01-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 412.72,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-02-08 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 415.2,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-04-28 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 457.8788,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.198,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-07-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 452.76,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 3,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-09-01 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 447.13,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 1,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-09-13 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 411.5721,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.229,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-10-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 488.8841,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.233,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-01-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 508.9894,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.188,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-04-30 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 514.175,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-05-06 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 528.215,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-05-24 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 529.435,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-06-05 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 545.05,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 1,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-07-01 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 544.0187,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.214,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-07-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 571.68,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 1,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-10-08 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "SPY",
    externalId: null,
    excludeFromHarvest: 0,
    price: 582.3762,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.202,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2024-10-31 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 70.8867,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 6,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2018-10-11 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 62.685,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 4,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2019-09-09 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 61,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 70,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-16 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 59.217,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 10,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2022-12-20 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 80.706,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-02-09 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 76.54,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 2,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-02-13 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 70.62,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 12,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-03-10 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 68.0944,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 80,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-03-13 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 57.765,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 100,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-03-23 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 56.6,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 10,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-08-21 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: "2024-12-15 23:42:43.739",
    updatedAt: "2024-12-15 23:42:43.739",
    positionId: null,
    assetSymbol: "XYZ",
    externalId: null,
    excludeFromHarvest: 0,
    price: 43.375,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 50,
    availableQty: null,
    orderNo: null,
    acquiredDate: "2023-11-02 00:00:00.000",
    exchangeRate: null,
    settlementCurrency: "USD",
    paymentCurrency: "USD",
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
];
