# Global configuration
global:
  namespace: harvester
  projectID: harvester-ai-428202
  clusterLocation: us-central1-b
  clusterName: harvester-dev

# Service account for GCP workload identity
serviceAccountName: google-secret-service-account

# Secret refresh interval
refreshInterval: 15m

# External Secrets configuration
externalSecrets:
  - name: database
    target: database
    data:
      - secretKey: DATABASE_URL
        remoteKey: DATABASE_URL

  # - name: clerk
  #   target: clerk
  #   data:
  #     - secretKey: CLERK_SECRET_KEY
  #       remoteKey: CLERK_SECRET_KEY

  # - name: stripe
  #   target: stripe
  #   data:
  #     - secretKey: STRIPE_SECRET_KEY
  #       remoteKey: STRIPE_SECRET_KEY
