mutation InitiateConnection($accountId: String!) {
  initiateConnection(accountId: $accountId)
}

fragment AccountLiveURLItem on Account {
  id
  liveURL
  liveURLCreated
}

query AccountLiveURL($accountId: String!) {
  account(id: $accountId) {
    ...AccountLiveURLItem
  }
}

mutation UpdateAccountLiveURL(
  $accountId: String!
  $accountUpdateInput: AccountUpdateInput!
) {
  updateAccount(
    accountWhereUniqueInput: { id: $accountId }
    accountUpdateInput: $accountUpdateInput
  ) {
    ...AccountLiveURLItem
  }
}
