query AccountMapping($where: AccountWhereInput) {
	accounts(where: $where) {
		id
		name
		plaidAccountMask
		type
		lotSeededDate
		files {
			id
			displayName
			createdAt
		}
	}
}

mutation ProcessCsvAccounts($accountIds: [String!]!) {
	processCsvAccounts(accountIds: $accountIds)
}
