fragment PortfolioTableItem on Portfolio {
  createdBy {
    name
    id
    photo
    email
  }
  createdById
  id
  name
  accounts {
    id
    status
    name
    institution
  }
  createdAt
  usersOnPortfolios {
    user {
      name
      id
      photo
      email
    }
    role
  }
}

query PortfolioTable {
  portfolios {
    ...PortfolioTableItem
  }
}
