fragment PortfolioTableItem on Portfolio {
	createdBy {
		name
		id
		photo
		email
	}
	createdById
	id
	name
	endOfYearTaxOpportunityNotification
	notificationFrequency
	accounts {
		id
		status
		name
	}
	createdAt
	usersOnPortfolios {
		user {
			name
			id
			photo
			email
		}
		role
	}
}

query PortfolioTable {
	portfolios {
		id
		...PortfolioTableItem
	}
}
mutation UpdatePortfolio($data: PortfolioUpdateInput!) {
	updatePortfolio(data: $data) {
		...PortfolioDetailItem
	}
}
