---
# Database URL secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-external-secret
  namespace: harvester
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: database
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL # The name of the secret in Google Secret Manager

---
# Clerk secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clerk-external-secret
  namespace: harvester
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: clerk
    creationPolicy: Owner
  data:
    - secretKey: CLERK_SECRET_KEY
      remoteRef:
        key: CLERK_SECRET_KEY # The name of the secret in Google Secret Manager

---
# Stripe secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stripe-external-secret
  namespace: harvester
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: stripe
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: STRIPE_SECRET_KEY # The name of the secret in Google Secret Manager
