apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: harvester-ai-428202 # Your GCP project ID
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: google-secret-service-account
            namespace: harvester
          clusterLocation: us-central1-b # GKE cluster region
          clusterName: harvester-dev # GKE cluster name
