---
# Source: harvester/charts/api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-api
  namespace: harvester
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: release-name
---
# Source: harvester/charts/web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-web
  namespace: harvester
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: release-name
---
# Source: harvester/charts/api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-api
  namespace: harvester
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
spec:
  replicas: 1
  revisionHistoryLimit: 2 # only keep last 2 old ReplicaSets
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: google-secret-service-account
      containers:
        - name: api
          image: 'us-central1-docker.pkg.dev/harvester-ai-428202/harvester-api/harvester-api:v1.2.1'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: CLIENT_HOME_PAGE_PATH
              value: /main/home
            - name: CLIENT_ORIGIN
              value: 'http://dev.taxharvest.ai'
            - name: CRON
              value: 'true'
            - name: ETRADE_HOSTNAME
              value: api.etrade.com
            - name: ETRADE_OAUTH_AUTHORIZE_URL
              value: 'https://us.etrade.com/e/t/etws/authorize'
            - name: GCS_LOTS_BUCKET_NAME
              value: lot_upload
            - name: GOOGLE_PROJECT
              value: harvester-ai-428202
            - name: ORIGIN
              value: 'https://dev.taxharvest.ai'
            - name: PLAID_ENV
              value: 'https://production.plaid.com'
            - name: PORT
              value: '8000'
            - name: SECRET_SOURCE
              value: GCP
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DATABASE_URL
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk
                  key: CLERK_SECRET_KEY
          resources:
            {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            intervalSeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
        # Cloud SQL Auth Proxy sidecar container
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
            - --private-ip
            # - "--unix-socket=/cloudsql"
            - --port=5432
            - 'harvester-ai-428202:us-central1:harvester-dev'
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          resources:
            {}
      volumes:
        - name: cloudsql
          emptyDir: {}
---
# Source: harvester/charts/web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-web
  namespace: harvester
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
spec:
  replicas: 1
  revisionHistoryLimit: 2 # only keep last 2 old ReplicaSets
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: google-secret-service-account
      containers:
        - name: web
          image: 'us-central1-docker.pkg.dev/harvester-ai-428202/harvester-web/harvester-web:v1.2.1'
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3000'
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk
                  key: CLERK_SECRET_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: STRIPE_SECRET_KEY
          resources:
            {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
---
# Source: harvester/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harvester-ingress
  namespace: harvester
  labels:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.allow-http: 'true'
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: harvester-static-ip
    networking.gke.io/managed-certificates: harvester-cert
spec:
  ingressClassName:
  rules:
    - host: dev.taxharvest.ai
      http:
        paths:
          # API service path
          - path: /core
            pathType: Prefix
            backend:
              service:
                name: release-name-api
                port:
                  number: 80
          # Web frontend path
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-name-web
                port:
                  number: 80
---
# Source: harvester/charts/secrets/templates/secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: harvester-ai-428202
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: google-secret-service-account
            namespace: harvester
          clusterLocation: us-central1-b
          clusterName: harvester-dev
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-external-secret
  namespace: harvester
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: database
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
---
# Source: harvester/templates/managed-certificate.yaml
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: harvester-cert
  namespace: harvester
  labels:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  domains:
    - dev.taxharvest.ai
---
# Source: harvester/charts/api/templates/migrations.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-api-migrations
  namespace: harvester
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
    app.kubernetes.io/component: migrations
  annotations:
    # This is what tells Helm to wait for the job to complete
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '-100'
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: migrations
    spec:
      serviceAccountName: google-secret-service-account
      shareProcessNamespace: true
      restartPolicy: Never
      containers:
        - name: migrations
          image: 'us-central1-docker.pkg.dev/harvester-ai-428202/harvester-api/harvester-api:v1.2.1'
          imagePullPolicy: Always
          command: [/bin/sh, -c]
          args: ["set -e\necho \"Running database migration...\"\nif ! npx prisma migrate deploy; then\n  echo \"Migration failed\"\n  exit 1\nfi\necho \"Migration completed successfully\"\n\necho \"Gracefully terminating Cloud SQL Auth Proxy sidecar...\"\nif pgrep -f cloud-sql-proxy \u003e /dev/null; then\n  pkill -TERM -f cloud-sql-proxy\n  sleep 5\n  if pgrep -f cloud-sql-proxy \u003e /dev/null; then\n    echo \"Forcing termination of proxy...\"\n    if ! pkill -9 -f cloud-sql-proxy 2\u003e/dev/null; then\n      echo \"Warning: Failed to force kill the proxy. It may have already exited.\"\n    fi\n  fi\nfi\n\necho \"Migration job complete\"\nexit 0\n"]
          env:
            # Add Cloud SQL instance connection name as an environment variable
            - name: INSTANCE_CONNECTION_NAME
              value: 'harvester-ai-428202:us-central1:harvester-dev'
            - name: CLIENT_HOME_PAGE_PATH
              value: /main/home
            - name: CLIENT_ORIGIN
              value: 'http://dev.taxharvest.ai'
            - name: CRON
              value: 'true'
            - name: ETRADE_HOSTNAME
              value: api.etrade.com
            - name: ETRADE_OAUTH_AUTHORIZE_URL
              value: 'https://us.etrade.com/e/t/etws/authorize'
            - name: GCS_LOTS_BUCKET_NAME
              value: lot_upload
            - name: GOOGLE_PROJECT
              value: harvester-ai-428202
            - name: ORIGIN
              value: 'https://dev.taxharvest.ai'
            - name: PLAID_ENV
              value: 'https://production.plaid.com'
            - name: PORT
              value: '8000'
            - name: SECRET_SOURCE
              value: GCP
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DATABASE_URL
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk
                  key: CLERK_SECRET_KEY
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
        # Cloud SQL Auth Proxy sidecar container
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
            - --private-ip
            # - "--unix-socket=/cloudsql"
            - --port=5432
            - 'harvester-ai-428202:us-central1:harvester-dev'
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          resources:
            {}
          terminationGracePeriodSeconds: 60 # Allow the proxy to shut down gracefully
      volumes:
        - name: cloudsql
          emptyDir: {}
