---
# Source: harvester/charts/api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-api
  namespace: harvester-dev
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: release-name
---
# Source: harvester/charts/web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-web
  namespace: harvester-dev
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: release-name
---
# Source: harvester/charts/api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-api
  namespace: harvester-dev
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
spec:
  replicas: 1
  revisionHistoryLimit: 2 # only keep last 2 old ReplicaSets
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: google-secret-service-account
      containers:
        - name: api
          image: "us-central1-docker.pkg.dev/harvester-ai-428202/harvester-api/harvester-api:v3.1.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: CLIENT_HOME_PAGE_PATH
              value: /main/home
            - name: CLIENT_ORIGIN
              value: "https://dev.taxharvest.ai"
            - name: DEFAULT_EMAIL_ADDRESS
              value: support@taxharvest.ai
            - name: ETRADE_HOSTNAME
              value: api.etrade.com
            - name: ETRADE_OAUTH_AUTHORIZE_URL
              value: "https://us.etrade.com/e/t/etws/authorize"
            - name: ETRADE_OAUTH_TOKEN_URL
              value: "https://us.etrade.com/e/t/etws/token"
            - name: GCS_LOTS_BUCKET_NAME
              value: lot_upload
            - name: GOOGLE_PROJECT
              value: harvester-ai-428202
            - name: MATCH_PERCENTAGE_DIFFERENCE
              value: 33
            - name: NUETRAL_HARVEST_THRESHOLD
              value: "1000"
            - name: NUETRAL_HARVEST_TARGET
              value: -3000
            - name: ORIGIN
              value: "https://dev.taxharvest.ai/core"
            - name: PLAID_ENV
              value: "https://production.plaid.com"
            - name: PORT
              value: "8000"
            - name: STRIPE_PUBLISHABLE_KEY
              value: pk_test_51RMA1bCIs96aprc48ICF4qlFkUUWlsfSnZw4xPQ4D43J775q4DkS1PPLFNdEu7cLyWFh6S0gRgk7W9FlFqwjZs1C00aQKxFWQW
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DATABASE_URL
            - name: DATABASE_URL_MIGRATION
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DATABASE_URL_MIGRATION
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk
                  key: CLERK_SECRET_KEY
            - name: CLERK_USER_UPDATE_CREATE_WEBHOOK_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: clerk
                  key: CLERK_USER_UPDATE_CREATE_WEBHOOK_SIGN_SECRET
            - name: ETRADE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: etrade
                  key: ETRADE_API_KEY
            - name: ETRADE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: etrade
                  key: ETRADE_API_SECRET
            - name: POLYGON_API_KEY
              valueFrom:
                secretKeyRef:
                  name: polygon
                  key: POLYGON_API_KEY
            - name: PLAID_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: plaid
                  key: PLAID_SECRET_KEY
            - name: PLAID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: plaid
                  key: PLAID_CLIENT_ID
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: STRIPE_SECRET_KEY
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid
                  key: SENDGRID_API_KEY
          resources: {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
        # Cloud SQL Auth Proxy sidecar container
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
            - --private-ip
            # - "--unix-socket=/cloudsql"
            - --port=5432
            - "harvester-ai-428202:us-central1:harvester-dev"
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          resources: {}
      volumes:
        - name: cloudsql
          emptyDir: {}
---
# Source: harvester/charts/web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-web
  namespace: harvester-dev
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
spec:
  replicas: 1
  revisionHistoryLimit: 2 # only keep last 2 old ReplicaSets
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: google-secret-service-account
      containers:
        - name: web
          image: "us-central1-docker.pkg.dev/harvester-ai-428202/harvester-web/harvester-web:v3.1.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk
                  key: CLERK_SECRET_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: STRIPE_SECRET_KEY
          resources: {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
---
# Source: harvester/charts/argocd/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations: null
spec:
  ingressClassName: gce
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
---
# Source: harvester/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harvester-ingress
  namespace: harvester-dev
  labels:
    app.kubernetes.io/name: harvester-dev
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: harvester-static-ip
    networking.gke.io/managed-certificates: harvester-dev-cert
spec:
  ingressClassName: gce
  rules:
    - host: dev.taxharvest.ai
      http:
        paths:
          - path: /core
            pathType: Prefix
            backend:
              service:
                name: release-name-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-name-web
                port:
                  number: 80
---
# Source: harvester/charts/secrets/templates/secretstore.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: harvester-ai-428202
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: google-secret-service-account
            namespace: harvester-dev
          clusterLocation: us-central1-b
          clusterName: harvester-dev
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-external-secret
  namespace: harvester-dev
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: database
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: DATABASE_URL_MIGRATION
      remoteRef:
        key: DATABASE_URL_MIGRATION
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clerk-external-secret
  namespace: harvester-dev
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: clerk
    creationPolicy: Owner
  data:
    - secretKey: CLERK_SECRET_KEY
      remoteRef:
        key: CLERK_SECRET_KEY
    - secretKey: CLERK_USER_UPDATE_CREATE_WEBHOOK_SIGN_SECRET
      remoteRef:
        key: CLERK_USER_UPDATE_CREATE_WEBHOOK_SIGN_SECRET
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stripe-external-secret
  namespace: harvester-dev
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: stripe
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: STRIPE_SECRET_KEY
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: etrade-external-secret
  namespace: harvester-dev
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: etrade
    creationPolicy: Owner
  data:
    - secretKey: ETRADE_API_KEY
      remoteRef:
        key: ETRADE_API_KEY
    - secretKey: ETRADE_API_SECRET
      remoteRef:
        key: ETRADE_API_SECRET
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: polygon-external-secret
  namespace: harvester-dev
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: polygon
    creationPolicy: Owner
  data:
    - secretKey: POLYGON_API_KEY
      remoteRef:
        key: POLYGON_API_KEY
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plaid-external-secret
  namespace: harvester-dev
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: plaid
    creationPolicy: Owner
  data:
    - secretKey: PLAID_SECRET_KEY
      remoteRef:
        key: PLAID_SECRET_KEY
    - secretKey: PLAID_CLIENT_ID
      remoteRef:
        key: PLAID_CLIENT_ID
---
# Source: harvester/charts/secrets/templates/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sendgrid-external-secret
  namespace: harvester-dev
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: sendgrid
    creationPolicy: Owner
  data:
    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: SENDGRID_API_KEY
---
# Source: harvester/templates/managed-certificate.yaml
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: harvester-dev-cert
  namespace: harvester-dev
  labels:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  domains:
    - dev.taxharvest.ai
---
# Source: harvester/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: google-secret-service-account
  namespace: harvester-dev
  labels:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    iam.gke.io/gcp-service-account: harvester-secret-manager@harvester-ai-428202.iam.gserviceaccount.com
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-200"
---
# Source: harvester/charts/api/templates/migrations.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-api-migrations
  namespace: harvester-dev
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: harvester
    app.kubernetes.io/component: migrations
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-50"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 30
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: migrations
    spec:
      serviceAccountName: google-secret-service-account
      shareProcessNamespace: true
      restartPolicy: Never
      containers:
        - name: migrations
          image: "us-central1-docker.pkg.dev/harvester-ai-428202/harvester-api/harvester-api:v3.1.1"
          imagePullPolicy: Always
          command: [/bin/sh, -c]
          args:
            [
              "chmod +x /app/scripts/migrate.sh \u0026\u0026 /app/scripts/migrate.sh\n",
            ]
          env:
            # Add Cloud SQL instance connection name as an environment variable
            - name: INSTANCE_CONNECTION_NAME
              value: "harvester-ai-428202:us-central1:harvester-dev"
            # Add general environment variables except secrets
            - name: CLIENT_HOME_PAGE_PATH
              value: /main/home
            - name: CLIENT_ORIGIN
              value: "https://dev.taxharvest.ai"
            - name: DEFAULT_EMAIL_ADDRESS
              value: support@taxharvest.ai
            - name: ETRADE_HOSTNAME
              value: api.etrade.com
            - name: ETRADE_OAUTH_AUTHORIZE_URL
              value: "https://us.etrade.com/e/t/etws/authorize"
            - name: ETRADE_OAUTH_TOKEN_URL
              value: "https://us.etrade.com/e/t/etws/token"
            - name: GCS_LOTS_BUCKET_NAME
              value: lot_upload
            - name: GOOGLE_PROJECT
              value: harvester-ai-428202
            - name: MATCH_PERCENTAGE_DIFFERENCE
              value: "0.3"
            - name: NUETRAL_HARVEST_THRESHOLD
              value: "1000"
            - name: ORIGIN
              value: "https://dev.taxharvest.ai/core"
            - name: PLAID_ENV
              value: "https://production.plaid.com"
            - name: PORT
              value: "8000"
            - name: STRIPE_PUBLISHABLE_KEY
              value: pk_test_51RMA1bCIs96aprc48ICF4qlFkUUWlsfSnZw4xPQ4D43J775q4DkS1PPLFNdEu7cLyWFh6S0gRgk7W9FlFqwjZs1C00aQKxFWQW
            # Add migration-specific environment variables
            # Add migration-specific secrets (these will override any general secrets)
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: DATABASE_URL_MIGRATION
          #
          #
          # volumeMounts:
          #   - name: cloudsql
          #     mountPath: /cloudsql
          #
          #
        # Cloud SQL Auth Proxy sidecar container
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
            - --private-ip
            # - "--unix-socket=/cloudsql"
            - --port=5432
            # Enable the admin api server on port 9091
            - --admin-port=9091
            # Enable the /quitquitquit admin api endpoint
            - --quitquitquit
            # Tell the proxy to exit gracefully if it receives a SIGTERM
            - --exit-zero-on-sigterm
            - "harvester-ai-428202:us-central1:harvester-dev"
          # volumeMounts:
          #   - name: cloudsql
          #     mountPath: /cloudsql
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          lifecycle:
            preStop:
              exec:
                command: [/bin/sh, -c, sleep 1]
          resources: {}
      volumes:
        - name: cloudsql
          emptyDir: {}
