apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: harvester-cert
  namespace: harvester
  labels:
    app: harvester
    component: ingress
spec:
  domains:
    - dev.taxharvest.ai
