global:
  namespace: harvester-dev
  environment: development
  domain: dev.taxharvest.ai
  domains:
    - dev.taxharvest.ai
    - argocd.dev.taxharvest.ai
  ingress:
    enabled: true
    className: gce
    annotations:
      # networking.gke.io/managed-certificates: harvester-dev-cert
      kubernetes.io/ingress.global-static-ip-name: harvester-static-ip
      kubernetes.io/ingress.allow-http: 'true'
      kubernetes.io/ingress.class: gce
    rules:
      - host: dev.taxharvest.ai
        paths:
          - path: /core
            pathType: Prefix
            service: api
          - path: /
            pathType: Prefix
            service: web
