global:
  namespace: harvester-prod
  environment: production
  ingress:
    enabled: true
    className: gce
    annotations:
      kubernetes.io/ingress.global-static-ip-name: harvester-prod-static-ip
      kubernetes.io/ingress.allow-http: 'false'
      kubernetes.io/ingress.class: gce
      networking.gke.io/managed-certificates: harvester-prod-cert
    rules:
      - host: taxharvest.ai
        paths:
          - path: /core
            pathType: Prefix
            service: api
          - path: /
            pathType: Prefix
            service: web
      - host: argocd.taxharvest.ai
        paths:
          - path: /
            pathType: Prefix
            service: argocd-server
            port: https
