global:
  namespace: harvester-dev
  environment: development
  ingress:
    enabled: true
    className: gce
    annotations:
      networking.gke.io/managed-certificates: harvester-dev-cert
      kubernetes.io/ingress.global-static-ip-name: harvester-static-ip
      kubernetes.io/ingress.allow-http: 'false'
      kubernetes.io/ingress.class: gce
    rules:
      - host: dev.taxharvest.ai
        paths:
          - path: /core
            pathType: Prefix
            service: api
          - path: /
            pathType: Prefix
            service: web

argocd:
  enabled: true
  ingress:
    enabled: true
    annotations:
      networking.gke.io/managed-certificates: argocd-dev-cert
      kubernetes.io/ingress.global-static-ip-name: argocd-dev-static-ip
      kubernetes.io/ingress.allow-http: 'false'
      kubernetes.io/ingress.class: gce
    host: argocd.dev.taxharvest.ai
    path: /
    pathType: Prefix
    service:
      name: argocd-server
      port:
        name: https
