global:
  namespace: harvester-prod
  environment: production
  certificates:
    - name: harvester-prod-cert
      namespace: harvester-prod
      domains:
        - app.taxharvest.ai
  ingress:
    enabled: true
    className: gce
    annotations:
      networking.gke.io/managed-certificates: harvester-prod-cert
      kubernetes.io/ingress.global-static-ip-name: prod-taxharvest-static-ip
      kubernetes.io/ingress.allow-http: "false"
      kubernetes.io/ingress.class: gce
    rules:
      - host: app.taxharvest.ai
        paths:
          - path: /core
            pathType: Prefix
            service: api
          - path: /
            pathType: Prefix
            service: web
api:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/harvester-ai-428202/harvester-api/harvester-api
    tag: v3.2.18
    pullPolicy: Always
  env:
    extras:
      PLAID_ENV: https://production.plaid.com
      ETRADE_OAUTH_AUTHORIZE_URL: https://us.etrade.com/e/t/etws/authorize
      ETRADE_OAUTH_TOKEN_URL: https://us.etrade.com/e/t/etws/token
      ETRADE_HOSTNAME: api.etrade.com
      GOOGLE_PROJECT: harvester-ai-428202
      GCS_LOTS_BUCKET_NAME: lot_upload_prod
      CLIENT_ORIGIN: https://app.taxharvest.ai
      ORIGIN: https://app.taxharvest.ai/core
      STRIPE_PUBLISHABLE_KEY: pk_live_5qIntVhFeqoTw1Pehq7YOJvx004hj6d7sk
web:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/harvester-ai-428202/harvester-web/harvester-web-prod
    tag: v3.2.18
    pullPolicy: Always
secrets:
  externalSecrets:
    - name: database
      target: database
      data:
        - secretKey: DATABASE_URL
          remoteKey: PROD_DATABASE_URL
        - secretKey: DATABASE_URL_MIGRATION
          remoteKey: PROD_DATABASE_URL_MIGRATION
    - name: clerk
      target: clerk
      data:
        - secretKey: CLERK_SECRET_KEY
          remoteKey: PROD_CLERK_SECRET_KEY
        - secretKey: CLERK_USER_UPDATE_CREATE_WEBHOOK_SIGN_SECRET
          remoteKey: PROD_CLERK_USER_UPDATE_CREATE_WEBHOOK_SIGN_SECRET
    - name: stripe
      target: stripe
      data:
        - secretKey: STRIPE_SECRET_KEY
          remoteKey: PROD_STRIPE_SECRET_KEY
    - name: etrade
      target: etrade
      data:
        - secretKey: ETRADE_API_KEY
          remoteKey: PROD_ETRADE_API_KEY
        - secretKey: ETRADE_API_SECRET
          remoteKey: PROD_ETRADE_API_SECRET
    - name: polygon
      target: polygon
      data:
        - secretKey: POLYGON_API_KEY
          remoteKey: PROD_POLYGON_API_KEY
    - name: plaid
      target: plaid
      data:
        - secretKey: PLAID_SECRET_KEY
          remoteKey: PROD_PLAID_SECRET_KEY
        - secretKey: PLAID_CLIENT_ID
          remoteKey: PROD_PLAID_CLIENT_ID
    - name: sendgrid
      target: sendgrid
      data:
        - secretKey: SENDGRID_API_KEY
          remoteKey: PROD_SENDGRID_API_KEY
# argocd:
#   enabled: true
#   namespace: argocd
# ingress:
#   enabled: true
# annotations:
#   networking.gke.io/managed-certificates: argocd-prod-cert
#   kubernetes.io/ingress.global-static-ip-name: prod-argo-taxharvest-static-ip
#   kubernetes.io/ingress.allow-http: "true"
#   kubernetes.io/ingress.class: gce
# host: argocd.taxharvest.ai
# path: /
# pathType: Prefix
# service:
#   name: argocd-server
#   port:
#     name: http
