fragment AccountTransactionItem on Account {
	id
	name
	authConnection {
		id
		source
	}
}

fragment TransactionTableItem on Transaction {
	id
	quantity
	type
	description
	assetSymbol
	settlementDate
	securityType
	displaySymbol
	# Plaid filled
	amount
	externalId
	fee
	memo
	price
	subtype
	transactionDate
	merged
	account {
		id
		...AccountTransactionItem
	}
}

query Transactions($where: TransactionWhereInput) {
	transactions(where: $where) {
		id
		...TransactionTableItem
	}
}
