name: PR Scope Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [trunk]

jobs:
  label-pr:
    name: 'PR labeler 🏷️'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: PR Scope Labeler 🏷️
        uses: actions/labeler@v5
        with:
          configuration-path: .github/pr-scope-labeler.yml
          sync-labels: true
