fragment HarvestTableItem on Harvest {
  id
  date
  type
  step
  createdAt
  amount
  label
  createdBy {
    id
    # eslint-disable-next-line @graphql-eslint/known-fragment-names
    ...UserItem
  }
}

query Harvests($where: HarvestWhereInput) {
  harvests(where: $where) {
    id
    ...HarvestTableItem
  }
}
