query VerificationEtrade($portfolioId: String!) {
  requestOauthConnection(
    authSource: ETRADE_REQUEST
    portfolioId: $portfolioId
  ) {
    verificationUrl
  }
}

mutation OauthEtrade($verifier: String!, $portfolioId: String!) {
  accessOauthConnection(
    verifier: $verifier
    authSource: ETRADE_ACCESS
    portfolioId: $portfolioId
  ) {
    id
  }
}
