query PlaidLinkToken($authConnectionId: String) {
	linkToken(authConnectionId: $authConnectionId)
}
fragment PlaidAuthConnection on AuthConnection {
	id
	plaidInstitutionId
	authedAt
	syncedAt
	portfolioId
	user {
		id
		email
		phoneNumber
	}
	plaidInstitution {
		id
		logo
		name
		primaryColor
	}
	accounts {
		id
		name
		plaidAccountMask
		type
		subType
		status
		balanceAccount
		accountValueTotal
	}
}

query PlaidAuthConnections {
	plaidAuthConnections {
		...PlaidAuthConnection
	}
}

query PlaidInstitutionInfo($institutionId: String!) {
	plaidInstitutionInfo(institutionId: $institutionId) {
		institution_id
		name
		logo
		primary_color
		url
		products
		country_codes
	}
}

fragment PortfolioConnectPlaidSyncResult on PortfolioConnect {
	id
	plaidInstitutionId
	state
	persistedSnapshot
	createdAt
	updatedAt
	account {
		id
		name
		plaidAccountMask
		type
		subType
		status
		balanceAccount
		accountValueTotal
		positions {
			id
			assetSymbol
			pricePaid
			quantity
			dateAcquired
			dateExpiration
			commissionTotal
			feesOther
		}
	}
}

mutation PlaidSetAccessTokenAndSyncAccounts(
	$publicToken: String!
	$metaData: PlaidLinkOnSuccessMetadata!
	$existingPortfolioConnectId: String
) {
	setAccessTokenAndSyncAccounts(
		publicToken: $publicToken
		metaData: $metaData
		existingPortfolioConnectId: $existingPortfolioConnectId
	) {
		...PortfolioConnectPlaidSyncResult
	}
}
