query PlaidLinkToken {
  linkToken
}

mutation PlaidSetAccessTokenAndSyncAccounts(
  $publicToken: String!
  $metaData: PlaidLinkOnSuccessMetadata!
  $existingAccountId: String
) {
  setAccessTokenAndSyncAccounts(
    publicToken: $publicToken
    metaData: $metaData
    existingAccountId: $existingAccountId
  ) {
    id
  }
}

mutation PlaidSync($authConnectionId: String!) {
  syncAuthConnection(id: $authConnectionId) {
    id
  }
}
