export const allGainLots = [
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 19.386,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2014-09-03 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 40.001,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2014-09-04 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.227,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2019-08-15 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.175,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2019-11-14 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.143,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2020-02-13 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.164,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2020-05-14 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.109,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2020-08-13 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2020-09-01 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.112,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2020-11-12 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 1,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2020-11-19 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 5,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2021-01-06 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.108,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2021-02-11 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.126,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2021-05-13 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.107,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2021-08-12 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.106,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2021-11-11 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.091,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2022-02-10 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.116,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2022-05-12 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },
  {
    createdAt: '2024-12-15 23:42:43.739',
    updatedAt: '2024-12-15 23:42:43.739',
    positionId: null,
    assetSymbol: 'AAPL',
    externalId: null,
    excludeFromHarvest: 0,
    price: 1,
    gainDay: null,
    gainDayPct: null,
    marketValue: null,
    costTotal: null,
    totalCostForGainPct: null,
    gainTotal: null,
    originalQty: null,
    remainingQty: 0.097,
    availableQty: null,
    orderNo: null,
    acquiredDate: '2022-08-11 00:00:00.000',
    exchangeRate: null,
    settlementCurrency: 'USD',
    paymentCurrency: 'USD',
    adjPrice: null,
    commPerShare: null,
    feesPerShare: null,
    lotSourceCode: null,
    termCode: null,
    legNo: null,
    locationCode: null,
    shortType: null,
  },

]
